# Generated by Django 5.0.7 on 2025-02-16 13:43

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default=None, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='NodzUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('freetrial_enddate', models.DateTimeField(blank=True, null=True)),
                ('premium', models.BooleanField(default=False)),
                ('nodescounter', models.IntegerField(default=0)),
                ('pseudo', models.CharField(default='', max_length=150)),
                ('birthdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=2, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['nodescounter'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.PositiveIntegerField()),
                ('layer_name', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'layer_id')},
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.PositiveIntegerField(default=1)),
                ('linkA', models.TextField(default='')),
                ('linkB', models.TextField(default='')),
                ('archive', models.BooleanField(default=False)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='nodzapp.layer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'link_id'],
                'unique_together': {('user', 'link_id')},
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.PositiveIntegerField(default=1)),
                ('x_coordinate', models.FloatField(default=0)),
                ('y_coordinate', models.FloatField(default=0)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(default='text', max_length=50)),
                ('color', models.CharField(default='#33FF99', max_length=20)),
                ('transparent', models.BooleanField(default=False)),
                ('radius', models.FloatField(default=0)),
                ('links', models.TextField(default='')),
                ('siblings', models.TextField(default='')),
                ('quantum', models.TextField(default='')),
                ('lock', models.BooleanField(default=False)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video_content', models.TextField(blank=True, null=True)),
                ('video_link', models.TextField(blank=True, null=True)),
                ('canvas_content', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file', models.FileField(null=True, upload_to='uploads/')),
                ('preview', models.FileField(null=True, upload_to='uploads/')),
                ('file_text_content', models.TextField(blank=True, null=True)),
                ('notification', models.TextField(blank=True, null=True)),
                ('archive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='nodzapp.layer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'node_id'],
                'unique_together': {('user', 'node_id')},
            },
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.IntegerField(default=1)),
                ('rootX', models.FloatField(default=0)),
                ('rootY', models.FloatField(default=0)),
                ('nodecounter', models.IntegerField(default=0)),
                ('linkcounter', models.IntegerField(default=0)),
                ('layercounter', models.IntegerField(default=1)),
                ('sound', models.BooleanField(default=False)),
                ('dark', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('max_access', models.IntegerField(default=5)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('links', models.ManyToManyField(to='nodzapp.link')),
                ('nodes', models.ManyToManyField(to='nodzapp.node')),
                ('params', models.ManyToManyField(to='nodzapp.param')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.PositiveIntegerField(default=1)),
                ('x_coordinate', models.FloatField(default=0)),
                ('y_coordinate', models.FloatField(default=0)),
                ('type', models.CharField(default='text', max_length=50)),
                ('size', models.FloatField(default=0)),
                ('archive', models.BooleanField(default=False)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='nodzapp.layer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'template_id'],
                'unique_together': {('user', 'template_id')},
            },
        ),
    ]
