# Generated by Django 5.0.7 on 2025-02-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AddField(
            model_name='template',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
