# Generated by Django 5.0.7 on 2025-02-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0002_delete_uploadedfile_template_lock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='param',
            old_name='rootX',
            new_name='originX',
        ),
        migrations.RenameField(
            model_name='param',
            old_name='rootY',
            new_name='originY',
        ),
        migrations.AddField(
            model_name='param',
            name='fullscreen',
            field=models.BooleanField(default=False),
        ),
    ]
