# Generated by Django 5.0.7 on 2025-03-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0003_rename_rootx_param_originx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='transparent',
        ),
        migrations.AddField(
            model_name='node',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='node',
            name='shape',
            field=models.TextField(default='circle'),
        ),
    ]
