# Generated by Django 5.0.7 on 2025-03-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0004_remove_node_transparent_node_likes_node_shape'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodzuser',
            old_name='freetrial_enddate',
            new_name='premium_enddate',
        ),
        migrations.RemoveField(
            model_name='nodzuser',
            name='pseudo',
        ),
        migrations.AddField(
            model_name='nodzuser',
            name='verifcode',
            field=models.IntegerField(default=0),
        ),
    ]
