# Generated by Django 5.0.7 on 2025-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0005_rename_freetrial_enddate_nodzuser_premium_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/{user}/{layer}/'),
        ),
    ]
