# Generated by Django 5.0.7 on 2025-03-17 17:05

import nodzapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0006_alter_node_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='file',
            field=models.FileField(null=True, upload_to=nodzapp.models.user_layer_upload_to),
        ),
    ]
