# Generated by Django 5.0.7 on 2025-03-18 10:47

import nodzapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0007_alter_node_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to=nodzapp.models.user_layer_upload_to),
        ),
        migrations.AlterField(
            model_name='node',
            name='preview',
            field=models.FileField(null=True, upload_to=nodzapp.models.user_layer_upload_to),
        ),
    ]
