# Generated by Django 5.0.7 on 2025-03-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0008_alter_node_image_content_alter_node_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodzuser',
            name='username',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
