# Generated by Django 5.0.7 on 2025-03-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0010_feedback'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='nodzuser',
            managers=[
            ],
        ),
    ]
