# Generated by Django 5.0.7 on 2025-03-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0011_alter_nodzuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodzuser',
            name='referree_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodzuser',
            name='referrees',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='nodzuser',
            name='referrer',
            field=models.IntegerField(default=0),
        ),
    ]
