# Generated by Django 5.0.7 on 2025-03-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodzapp', '0012_nodzuser_referree_points_nodzuser_referrees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodzuser',
            old_name='premium_enddate',
            new_name='premium_date',
        ),
        migrations.AddField(
            model_name='nodzuser',
            name='premium_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nodzuser',
            name='premium_type',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
